version: '3.7'

services:
  database-pgsql:
    image: postgres:15.3-alpine
    container_name: db_pg_ctas
    restart: on-failure
    ports:
      - "4040:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      POSTGRES_DB: ctas
      POSTGRES_USER: admin_ctas
      POSTGRES_PASSWORD: admin_ctas
    volumes:
      - database_data:/var/lib/postgresql
    networks:
      ctas-mg:
        ipv4_address: 192.168.20.3


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_ctas
    depends_on:
      - database-pgsql
    environment:
      - PGADMIN_DEFAULT_EMAIL=ga.randrianarivelo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminctas
    ports:
      - "5050:80"
    networks:
      ctas-mg:
        ipv4_address: 192.168.20.4




  adminer:
    image: adminer
    container_name: adminer_ctas
    restart: on-failure
    ports:
      - "7070:8080"
    networks:
      ctas-mg:
        ipv4_address: 192.168.20.5


  www:
      build: docker
      container_name: www_ctas
      restart: on-failure
      ports:
        - "8080:80"
      volumes:
        - ./docker/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
      networks:
        ctas-mg:
          ipv4_address: 192.168.20.2


networks:
  ctas-mg:
    name: ctas-mg
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

volumes:
  database_data:
